# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
# 
# Discord: https://discord.gg/papermc
# IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper ) 
# Website: https://papermc.io/ 
# Docs: https://paper.readthedocs.org/ 

verbose: false
config-version: 20
settings:
  use-alternative-luck-formula: false
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  console-has-all-permissions: false
  region-file-cache-size: 256
  incoming-packet-spam-threshold: 300
  max-joins-per-tick: 3
  track-plugin-scoreboards: false
  suggest-player-names-when-null-tab-completions: true
  chunk-tasks-per-tick: 1000
  save-player-data: true
  enable-player-collisions: true
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  save-empty-scoreboard-teams: false
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
  unsupported-settings:
    allow-headless-pistons: false
    allow-permanent-block-break-exploits: false
    allow-piston-duplication: false
    allow-headless-pistons-readme: This setting controls if players should be able
      to create headless pistons.
    allow-permanent-block-break-exploits-readme: This setting controls if players
      should be able to break bedrock, end portals and other intended to be permanent
      blocks.
    allow-piston-duplication-readme: This setting controls if player should be able
      to use TNT duplication, but this also allows duplicating carpet, rails and potentially
      other items
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  spam-limiter:
    recipe-spam-increment: 1
    recipe-spam-limit: 20
    tab-spam-increment: 1
    tab-spam-limit: 500
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  async-chunks:
    threads: -1
messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
  kick:
    authentication-servers-down: ''
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
  server-name: Unknown Server
world-settings:
  default:
    fix-climbing-bypassing-cramming-rule: false
    seed-based-feature-search: true
    should-remove-dragon: false
    optimize-explosions: true
    baby-zombie-movement-modifier: 0.5
    disable-teleportation-suffocation-check: false
    fixed-chunk-inhabited-time: -1
    use-vanilla-world-scoreboard-name-coloring: false
    remove-corrupt-tile-entities: true
    experience-merge-max-value: -1
    prevent-moving-into-unloaded-chunks: true
    max-auto-save-chunks-per-tick: 24
    count-all-mobs-for-spawning: false
    per-player-mob-spawns: true
    delay-chunk-unloads-by: 10s
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    filter-nbt-data-from-spawn-eggs-and-related: true
    max-entity-collisions: 8
    disable-creeper-lingering-effect: false
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    water-over-lava-flow-speed: 5
    grass-spread-tick-rate: 1
    use-faster-eigencraft-redstone: true
    nether-ceiling-void-damage-height: 0
    allow-non-player-entities-on-scoreboards: false
    portal-search-radius: 128
    portal-create-radius: 16
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    armor-stands-do-collision-entity-lookups: true
    keep-spawn-loaded: true
    disable-thunder: false
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-ice-and-snow: false
    keep-spawn-loaded-range: 10
    container-update-tick-rate: 1
    prevent-tnt-from-moving-in-water: false
    iron-golems-can-spawn-in-air: false
    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    spawner-nerfed-mobs-should-jump: false
    entities-target-with-follow-range: true
    zombies-target-turtle-eggs: true
    zombie-villager-infection-chance: -1.0
    armor-stands-tick: true
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 1
    light-queue-size: 20
    auto-save-interval: -1
    game-mechanics:
      fix-curing-zombie-villager-discount-exploit: true
      scan-for-legacy-ender-dragon: true
      disable-pillager-patrols: false
      disable-chest-cat-detection: false
      nerf-pigmen-from-nether-portals: false
      disable-player-crits: false
      disable-sprint-interruption-on-attack: false
      shield-blocking-delay: 5
      disable-end-credits: true
      disable-unloaded-chunk-enderpearl-exploit: true
      disable-relative-projectile-velocity: false
      pillager-patrols:
        spawn-chance: 0.2
        spawn-delay:
          per-player: false
          ticks: 12000
        start:
          per-player: false
          day: 5
    max-growth-height:
      cactus: 3
      reeds: 3
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    despawn-ranges:
      soft: 32
      hard: 128
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 24h
      refresh-max: 7d
    alt-item-despawn-rate:
      enabled: false
      items:
        COBBLESTONE: 300
    hopper:
      cooldown-when-full: true
      disable-move-event: false
    lightning-strike-distance-limit:
      sound: -1
      impact-sound: -1
      flash: -1
    anti-xray:
      enabled: true
      engine-mode: 1
      max-chunk-section-index: 3
      update-radius: 2
      lava-obscures: false
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - oak_planks
    viewdistances:
      no-tick-view-distance: -1
    squid-spawn-height:
      maximum: 0.0
    generator-settings:
      flat-bedrock: false
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 75
